services:
  app:
    build: . # Usa o Dockerfile na raiz do projeto
    ports:
      - '8000:8000' # Porta web
      - '50051:50051' # Porta gRPC
      - '3000:3000' # Porta GraphQL
    depends_on:
      - mysql
      - rabbitmq
    environment:
      - DB_HOST=mysql
      - RABBITMQ_HOST=rabbitmq

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
      - ./internal/infra/sql/init.sql:/docker-entrypoint-initdb.d/setup.sql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
